USE [master]
GO

/****** Object:  Database [TDM_Demo1]    Script Date: 4/3/2019 1:44:31 PM ******/
CREATE DATABASE [TDM_Demo1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TDM_Demo1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TDM_Demo1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TDM_Demo1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TDM_Demo1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TDM_Demo1] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TDM_Demo1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TDM_Demo1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TDM_Demo1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TDM_Demo1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TDM_Demo1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TDM_Demo1] SET ARITHABORT OFF 
GO

ALTER DATABASE [TDM_Demo1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TDM_Demo1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TDM_Demo1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TDM_Demo1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TDM_Demo1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TDM_Demo1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TDM_Demo1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TDM_Demo1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TDM_Demo1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TDM_Demo1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TDM_Demo1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TDM_Demo1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TDM_Demo1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TDM_Demo1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TDM_Demo1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TDM_Demo1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TDM_Demo1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TDM_Demo1] SET RECOVERY FULL 
GO

ALTER DATABASE [TDM_Demo1] SET  MULTI_USER 
GO

ALTER DATABASE [TDM_Demo1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TDM_Demo1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TDM_Demo1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TDM_Demo1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TDM_Demo1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TDM_Demo1] SET QUERY_STORE = OFF
GO

USE [TDM_Demo1]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [TDM_Demo1] SET  READ_WRITE 
GO

USE [TDM_Demo1]
GO

/****** Object:  Table [dbo].[Risk_CSV]    Script Date: 4/3/2019 1:53:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Risk_CSV](
	[account_id] [varchar](50) NULL,
	[amount] [varchar](50) NULL,
	[credit_score] [varchar](50) NULL,
	[reason] [varchar](50) NULL,
	[decision] [varchar](50) NULL,
	[message] [varchar](50) NULL
) ON [PRIMARY]
GO


